#!/usr/bin/env python3

import argparse
import sys
import dicepwd.epool
import dicepwd.charclasses

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-c', '--chars', type=int, dest='chars', help="How many characters are desired")
    parser.add_argument('-d', '--die-size', dest='die_size', type=int,
                        help="How many sides your dies have (mixed side counts not allowed)")
    args = parser.parse_args()

    character_class = dicepwd.charclasses.CharacterClass([chr(i) for i in range(33, 126)])

    def read_dice():
        while True:
            try:
                return dicepwd.epool.EntropyDrop(int(input('Roll d%d: ' % args.die_size)) - 1, args.die_size)
            except ValueError:
                print('Not an integer. Try again.')

    pool = dicepwd.epool.EntropyPool(entropy_source=read_dice)

    try:
        password = ''.join([
            character_class.pick(n)
            for n in [
                pool.pour(character_class.n)
                for i in range(args.chars)
            ]
        ])
    except EOFError:
        print('Aborted collecting rolls. Exiting.')
        sys.exit(1)

    print("Your new password: %s" % password)
